# Generated by Django 2.2.7 on 2020-02-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200, null=True)),
                ('brand', models.CharField(max_length=200, null=True)),
                ('model', models.CharField(max_length=200, null=True)),
                ('year', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('look1', models.CharField(max_length=500, null=True)),
                ('look2', models.CharField(max_length=500, null=True)),
                ('budget', models.IntegerField(null=True)),
                ('first_contact', models.CharField(max_length=1000, null=True)),
                ('to_contact', models.CharField(max_length=500, null=True)),
                ('communication', models.CharField(max_length=5000, null=True)),
                ('importance', models.IntegerField(null=True)),
            ],
        ),
    ]
