# Generated by Django 2.2.7 on 2020-03-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='files',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
