# Generated by Django 2.2.7 on 2020-03-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_app', '0004_auto_20200308_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientfile',
            old_name='client',
            new_name='clients',
        ),
        migrations.AlterField(
            model_name='clientfile',
            name='clientFile',
            field=models.FileField(null=True, upload_to='clientFiles'),
        ),
    ]
