# Generated by Django 3.0.3 on 2020-04-20 18:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients_app', '0005_auto_20200308_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfile',
            name='clientFile',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
