# Generated by Django 3.0.3 on 2020-04-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients_app', '0006_auto_20200420_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientfile',
            name='clientFile',
        ),
    ]
