# Generated by Django 3.0.3 on 2020-04-20 18:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients_app', '0007_remove_clientfile_clientfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfile',
            name='clientFile',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
