# Generated by Django 3.0.3 on 2020-04-20 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients_app', '0008_clientfile_clientfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientfile',
            name='clientFile',
        ),
    ]
