# Generated by Django 3.0.3 on 2020-06-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_app', '0010_clientfile_clientfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='description',
            new_name='equipment',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='brand',
            new_name='model_interest',
        ),
        migrations.RemoveField(
            model_name='client',
            name='look1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='look2',
        ),
        migrations.AddField(
            model_name='client',
            name='other_interests',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='year_interest',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='to_contact_text',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
