# Generated by Django 3.0.3 on 2020-06-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_app', '0011_auto_20200624_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='equipment_interest',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
