# Generated by Django 3.0.8 on 2020-08-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients_app', '0012_client_equipment_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientfile',
            name='clientFile',
        ),
    ]
