# Generated by Django 3.0.8 on 2020-08-01 17:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients_app', '0013_remove_clientfile_clientfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfile',
            name='clientFile',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
