# Generated by Django 3.0.8 on 2020-08-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_app', '0014_clientfile_clientfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
