# Generated by Django 2.2.7 on 2020-03-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='boat_description',
        ),
        migrations.RemoveField(
            model_name='boat',
            name='boat_name',
        ),
        migrations.RemoveField(
            model_name='boat',
            name='boat_price',
        ),
        migrations.AddField(
            model_name='boat',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='engine',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='engine_hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='equipment',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='model',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='owner',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='price',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
