# Generated by Django 3.0.3 on 2020-04-19 20:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0002_auto_20200301_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
