# Generated by Django 3.0.3 on 2020-04-20 10:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0004_auto_20200420_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
