# Generated by Django 3.0.8 on 2020-08-01 11:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0006_auto_20200420_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='boatFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boatFile', cloudinary.models.CloudinaryField(max_length=255, null=True)),
                ('boat', models.ManyToManyField(to='boats.Boat')),
            ],
        ),
    ]
