# Generated by Django 3.0.8 on 2020-08-01 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0007_boatfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boatfile',
            old_name='boat',
            new_name='boats',
        ),
    ]
