# Generated by Django 3.0.8 on 2020-08-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0008_auto_20200801_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boatfile',
            name='boatFile',
        ),
    ]
