# Generated by Django 3.0.8 on 2020-08-01 17:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0009_remove_boatfile_boatfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatfile',
            name='boatFile',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
