# Generated by Django 3.0.8 on 2020-08-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0011_auto_20200805_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='model',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
